import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'

// import '@/services/firebase'

import { AuthContextProvider } from '@/contexts/AuthContext'

// import { Header } from '@/components/Header'

import './globals.css'

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={roboto.className}>
        <main className="max-w-7xl mx-auto py-2">
          <AuthContextProvider>
            {/* <Header /> */}
            {children}
          </AuthContextProvider>
        </main>
      </body>
    </html>
  )
}
