import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'

import { Header } from '@/components/Header'

import './globals.css'

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header />

        <main className="max-w-7xl mx-auto py-12 px-4">
          {children}
        </main>
      </body>
    </html>
  )
}
